### ISSUE TITLE
Create Customer Login

### ISSUE THREAD

**Issue by garrett-vangilder** [TeamCharles/initial-site#6] opened 2016-10-19 20:23 UTC
### Feature Description

This feature will allow for a user to select a profile from a drop down menu. 
### Requirement to Fulfill

> Refer to the [project requirements](https://github.com/TeamCharles/bangazon-inc/blob/master/projects/INITIAL_BANGAZON_SITE.md#requirements) before filling out this section.

1.) In navigation bar, have a select element that allows you to pick which customer is active.
2.) Drop down must show all users that are included in the database. 
3.) User must be able to select a user and it must display the active user in the navbar.

**Comment by MattKraatz** [comment] 2016-10-24 23:36
Duplicate of #62 that @daynewright is working on.

**Closed as completed by MattKraatz** 2016-10-24 23:36 UTC
Labels: View, Controller
